/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignupRouteImport } from './app/signup'
import { Route as LoginRouteImport } from './app/login'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './app/_authenticated/index'
import { Route as AuthenticatedVendasRouteImport } from './app/_authenticated/vendas'
import { Route as AuthenticatedCreateRouteImport } from './app/_authenticated/create'
import { Route as AuthenticatedConfigRouteImport } from './app/_authenticated/config'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as AuthenticatedEventEventIdRouteImport } from './app/_authenticated/event/$eventId'
import { Route as AuthenticatedEventEventIdLiveRouteImport } from './app/_authenticated/event/$eventId/live'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventEventIdRoute =
  AuthenticatedEventEventIdRouteImport.update({
    id: '/event/$eventId',
    path: '/event/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventEventIdLiveRoute =
  AuthenticatedEventEventIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedEventEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/config': typeof AuthenticatedConfigRoute
  '/create': typeof AuthenticatedCreateRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/event/$eventId': typeof AuthenticatedEventEventIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/$eventId/live': typeof AuthenticatedEventEventIdLiveRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/config': typeof AuthenticatedConfigRoute
  '/create': typeof AuthenticatedCreateRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
  '/event/$eventId': typeof AuthenticatedEventEventIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/$eventId/live': typeof AuthenticatedEventEventIdLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/event/$eventId': typeof AuthenticatedEventEventIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/event/$eventId/live': typeof AuthenticatedEventEventIdLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/config'
    | '/create'
    | '/vendas'
    | '/event/$eventId'
    | '/api/auth/$'
    | '/event/$eventId/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/config'
    | '/create'
    | '/vendas'
    | '/'
    | '/event/$eventId'
    | '/api/auth/$'
    | '/event/$eventId/live'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/config'
    | '/_authenticated/create'
    | '/_authenticated/vendas'
    | '/_authenticated/'
    | '/_authenticated/event/$eventId'
    | '/api/auth/$'
    | '/_authenticated/event/$eventId/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/event/$eventId': {
      id: '/_authenticated/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AuthenticatedEventEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event/$eventId/live': {
      id: '/_authenticated/event/$eventId/live'
      path: '/live'
      fullPath: '/event/$eventId/live'
      preLoaderRoute: typeof AuthenticatedEventEventIdLiveRouteImport
      parentRoute: typeof AuthenticatedEventEventIdRoute
    }
  }
}

interface AuthenticatedEventEventIdRouteChildren {
  AuthenticatedEventEventIdLiveRoute: typeof AuthenticatedEventEventIdLiveRoute
}

const AuthenticatedEventEventIdRouteChildren: AuthenticatedEventEventIdRouteChildren =
  {
    AuthenticatedEventEventIdLiveRoute: AuthenticatedEventEventIdLiveRoute,
  }

const AuthenticatedEventEventIdRouteWithChildren =
  AuthenticatedEventEventIdRoute._addFileChildren(
    AuthenticatedEventEventIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventEventIdRoute: typeof AuthenticatedEventEventIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventEventIdRoute: AuthenticatedEventEventIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
